# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PositionService_pb2 as src_dot_pycam_dot_proto_dot_PositionService__pb2


class PositionServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPosition = channel.unary_unary(
                '/object_position.PositionService/SendPosition',
                request_serializer=src_dot_pycam_dot_proto_dot_PositionService__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_pycam_dot_proto_dot_PositionService__pb2.Position.FromString,
                )


class PositionServiceServicer(object):
    """The service definition.
    """

    def SendPosition(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PositionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPosition,
                    request_deserializer=src_dot_pycam_dot_proto_dot_PositionService__pb2.Empty.FromString,
                    response_serializer=src_dot_pycam_dot_proto_dot_PositionService__pb2.Position.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'object_position.PositionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PositionService(object):
    """The service definition.
    """

    @staticmethod
    def SendPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_position.PositionService/SendPosition',
            src_dot_pycam_dot_proto_dot_PositionService__pb2.Empty.SerializeToString,
            src_dot_pycam_dot_proto_dot_PositionService__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
